'use client';
import {
  BookOpen,
  Calendar,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  Edit,
  Film,
  Gamepad2,
  Home,
  LayoutGrid,
  Lightbulb,
  MoreHorizontal,
  Plus,
  Send,
  Sparkles,
  Star,
  Swords,
  Target,
  Trash2,
  Users,
  X,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: Lightbulb,
  home: Home,
  interest: Lightbulb,
  topic: BookOpen,
  goal: Target,
  task: CheckSquare,
  add: Plus,
  close: X,
  calendar: Calendar,
  ai: Sparkles,
  delete: Trash2,
  down: ChevronDown,
  up: ChevronUp,
  right: ChevronRight,
  left: ChevronLeft,
  ellipsis: MoreHorizontal,
  edit: Edit,
  grid: LayoutGrid,
  copy: Copy,
  game: Gamepad2,
  trueOrDare: Swords,
  luckyPin: Star,
  watchTogether: Film,
  send: Send,
  users: Users,
};
